"""Add addons column to Booking

Revision ID: 6df9562b139b
Revises: 8be29ae95318
Create Date: 2025-07-25 14:12:29.341759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df9562b139b'
down_revision = '8be29ae95318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addons', sa.Text(), nullable=True))
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('addons')

    # ### end Alembic commands ###
